In [1]:
# Bismillah

In [6]:
import numpy as np
import pandas as pd
import datetime as dt
# from datetime import datetime
import matplotlib.pyplot as plt
%matplotlib inline
pd.set_option('precision', 7)
from pandas_datareader import data as web

In [7]:
msft = web.DataReader('MSFT', 'yahoo', '2012-01-01', '2013-12-30')
msft

# collects the data from yahoo finance for Microsoft for the said period and stores it in data frame, msft.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6231384
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1320133
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.3581734
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7055092
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4066372
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.3362389
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7298546
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.0379219
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9095650
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9095650

### Shifting and lagging time-series data:

In [8]:
msftAC = msft['Adj Close']
msftAC

# select only 'Adj Close' column from the msft data frame, and store it in a series, msftAC.

Date
2012-01-03    21.6231384
2012-01-04    22.1320133
2012-01-05    22.3581734
2012-01-06    22.7055092
2012-01-09    22.4066372
                 ...
2013-12-23    31.3362389
2013-12-24    31.7298546
2013-12-26    32.0379219
2013-12-27    31.9095650
2013-12-30    31.9095650
Name: Adj Close, Length: 501, dtype: float64

In [4]:
type(msftAC)

# msftAC is a series. We can convert it to a data frame by typing: msftAC = msft[['Adj Close']]

pandas.core.series.Series

In [7]:
shift_forward = msftAC.shift(1)
msftAC.head(), shift_forward.head()
# This will shift the prices one day forward.
# results in one NaN value at the start since there was no value prior to be shifted to 2012-01-03.
# the number of NaN values will depend on the number of indices we are shifting forward or backward. For instance, the index is 
# daily dates, so if we shift one day forward, it means we are forwarding one index resulting into one NaN value. If we would 
# shift 2 days forward, it means we are forwarding two indices resulting into two NaN values.

(Date
 2012-01-03    21.6231346
 2012-01-04    22.1320076
 2012-01-05    22.3581734
 2012-01-06    22.7055054
 2012-01-09    22.4066391
 Name: Adj Close, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6231346
 2012-01-05    22.1320076
 2012-01-06    22.3581734
 2012-01-09    22.7055054
 Name: Adj Close, dtype: float64)

In [8]:
msftAC.tail(), shift_forward.tail()
# the last price 31.9755402 on date 2013-12-30 in msftAC has been lost away in shift_forward since there is no index available for
# it now after the prices have been shifted one day forward. So, we got one NaN value at the start and one value lost at the end
# by shifting one day forward.

(Date
 2013-12-23    31.3362350
 2013-12-24    31.7298698
 2013-12-26    32.0379257
 2013-12-27    31.9095612
 2013-12-30    31.9095612
 Name: Adj Close, dtype: float64,
 Date
 2013-12-23    31.4902592
 2013-12-24    31.3362350
 2013-12-26    31.7298698
 2013-12-27    32.0379257
 2013-12-30    31.9095612
 Name: Adj Close, dtype: float64)

In [9]:
shift_backward = msftAC.shift(-2)
# will shift two days (two indices) backward.

In [10]:
msftAC, shift_backward
# inserts two NaNs at the end since we have shifted two days (two indices) backward and the first two values lost since there are 
# no indices available for them.

(Date
 2012-01-03    21.6231346
 2012-01-04    22.1320076
 2012-01-05    22.3581734
 2012-01-06    22.7055054
 2012-01-09    22.4066391
                  ...
 2013-12-23    31.3362350
 2013-12-24    31.7298698
 2013-12-26    32.0379257
 2013-12-27    31.9095612
 2013-12-30    31.9095612
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03    22.3581734
 2012-01-04    22.7055054
 2012-01-05    22.4066391
 2012-01-06    22.4874153
 2012-01-09    22.3904819
                  ...
 2013-12-23    32.0379257
 2013-12-24    31.9095612
 2013-12-26    31.9095612
 2013-12-27           NaN
 2013-12-30           NaN
 Name: Adj Close, Length: 501, dtype: float64)

In [11]:
shift_1sec = msftAC.shift(1, freq = 'S')

In [12]:
msftAC, shift_1sec
# the prices have been shifted just one second forward each day. That means that the prices still exist on the same date. So, no
# value is lost and no NaN is inserted.
# the frequency could be changed to any desirable level such as hour etc.
# Note that the index labels have been adjusted according to the specified frequency resulting into a new dataframe or series in 
# this case.

(Date
 2012-01-03    21.6231384
 2012-01-04    22.1320133
 2012-01-05    22.3581734
 2012-01-06    22.7055092
 2012-01-09    22.4066372
                  ...
 2013-12-23    31.3362389
 2013-12-24    31.7298546
 2013-12-26    32.0379219
 2013-12-27    31.9095650
 2013-12-30    31.9095650
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03 00:00:01    21.6231384
 2012-01-04 00:00:01    22.1320133
 2012-01-05 00:00:01    22.3581734
 2012-01-06 00:00:01    22.7055092
 2012-01-09 00:00:01    22.4066372
                           ...
 2013-12-23 00:00:01    31.3362389
 2013-12-24 00:00:01    31.7298546
 2013-12-26 00:00:01    32.0379219
 2013-12-27 00:00:01    31.9095650
 2013-12-30 00:00:01    31.9095650
 Name: Adj Close, Length: 501, dtype: float64)

In [13]:
shift_1sec['2012-01-03':'2012-01-06']
# note that the indices now include the time as well in addition to the date.

Date
2012-01-03 00:00:01    21.6231384
2012-01-04 00:00:01    22.1320133
2012-01-05 00:00:01    22.3581734
2012-01-06 00:00:01    22.7055092
Name: Adj Close, dtype: float64

### Practical Example:

In [14]:
msftAC, msftAC.shift(1)
# the prices have been shifted one day forward.

(Date
 2012-01-03    21.6231384
 2012-01-04    22.1320133
 2012-01-05    22.3581734
 2012-01-06    22.7055092
 2012-01-09    22.4066372
                  ...
 2013-12-23    31.3362389
 2013-12-24    31.7298546
 2013-12-26    32.0379219
 2013-12-27    31.9095650
 2013-12-30    31.9095650
 Name: Adj Close, Length: 501, dtype: float64,
 Date
 2012-01-03           NaN
 2012-01-04    21.6231384
 2012-01-05    22.1320133
 2012-01-06    22.3581734
 2012-01-09    22.7055092
                  ...
 2013-12-23    31.4902630
 2013-12-24    31.3362389
 2013-12-26    31.7298546
 2013-12-27    32.0379219
 2013-12-30    31.9095650
 Name: Adj Close, Length: 501, dtype: float64)

In [15]:
msftAC/msftAC

Date
2012-01-03    1.0
2012-01-04    1.0
2012-01-05    1.0
2012-01-06    1.0
2012-01-09    1.0
             ...
2013-12-23    1.0
2013-12-24    1.0
2013-12-26    1.0
2013-12-27    1.0
2013-12-30    1.0
Name: Adj Close, Length: 501, dtype: float64

In [16]:
msftAC / msftAC.shift(1)
# the dividsion is based on the same index labels. That is, the price on 2012-01-04 in msftAC is divided the price on 2012-01-04 in
# msftAC.shift(1). This is equal t`o (current price divided by previous price). The previous price is the amount invested.

# Interpretation: the $1 invested has grown to $1.0235337. So, the net return is $1.0235337 - 1 = $0.0235337. That is why we need
# to subtract 1 as shown below.
# the first value is NaN because value is missing in msftAC.shift(1) on 2012-01-03.
# the last value is 1.00000 because in both msftAC and msftAC.shift(1) the value on 2013-12-30 is the same.

# Very important to note that we CANNOT say that $1 investment at the start (2012-01-03) has grown to (or in this case 
# has remained same) to $1 at the end of the period (2013-12-30) since we can see that the adj close price at the start
# is $21.62 and at the end is $31.90. So, there is definately a gain. But then why we have 1 at the end of the output of
# this cell? It is because these returns are computed on daily basis. So, this 1 shows that $1 dollar invested on 2013-12
#-27 has remained same $1 and it makes sense since the price has remained unchanged from 2013-12-27 to 2013-12-30. To find
# the total return, we need to find the cumulative product.

Date
2012-01-03          NaN
2012-01-04    1.0235337
2012-01-05    1.0102189
2012-01-06    1.0155349
2012-01-09    0.9868373
                ...
2013-12-23    0.9951088
2013-12-24    1.0125616
2013-12-26    1.0097087
2013-12-27    0.9959934
2013-12-30    1.0000000
Name: Adj Close, Length: 501, dtype: float64

In [16]:
np.cumprod(msftAC / msftAC.shift(1))

# just for the confirmation of the above.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339930
2012-01-06    1.0500561
2012-01-09    1.0362343
                ...
2013-12-23    1.4491994
2013-12-24    1.4674028
2013-12-26    1.4816499
2013-12-27    1.4757139
2013-12-30    1.4757139
Name: Adj Close, Length: 501, dtype: float64

In [17]:
31.9095650 / 21.6231346

# just for the confirmation above

1.4757141177856794

In [18]:
percent_change = msftAC / msftAC.shift(1) - 1
percent_change
# gives the net daily change or return.
# the price has increased by 2.3% from 2012-01-03 to 2012-01-04.

Date
2012-01-03          NaN
2012-01-04    0.0235338
2012-01-05    0.0102187
2012-01-06    0.0155351
2012-01-09   -0.0131630
                ...
2013-12-23   -0.0048912
2013-12-24    0.0125610
2013-12-26    0.0097091
2013-12-27   -0.0040064
2013-12-30    0.0000000
Name: Adj Close, Length: 501, dtype: float64

### Frequency Conversion of Time-Series Data:

In [47]:
sample = msftAC[:2]
sample
# selected first 2 rows and stored them in 'sample'

Date
2012-01-03    21.6231384
2012-01-04    22.1320133
Name: Adj Close, dtype: float64

In [48]:
sample.asfreq('H')
# to have hourly data between the two index labels.
# a new index with hourly index labels has been created by pandas, but when aligning to the original time series, only two values
# were found, thereby leaving the others filled with NaN. This default behaviour can be changed as follows:

Date
2012-01-03 00:00:00    21.6231384
2012-01-03 01:00:00           NaN
2012-01-03 02:00:00           NaN
2012-01-03 03:00:00           NaN
2012-01-03 04:00:00           NaN
2012-01-03 05:00:00           NaN
2012-01-03 06:00:00           NaN
2012-01-03 07:00:00           NaN
2012-01-03 08:00:00           NaN
2012-01-03 09:00:00           NaN
2012-01-03 10:00:00           NaN
2012-01-03 11:00:00           NaN
2012-01-03 12:00:00           NaN
2012-01-03 13:00:00           NaN
2012-01-03 14:00:00           NaN
2012-01-03 15:00:00           NaN
2012-01-03 16:00:00           NaN
2012-01-03 17:00:00           NaN
2012-01-03 18:00:00           NaN
2012-01-03 19:00:00           NaN
2012-01-03 20:00:00           NaN
2012-01-03 21:00:00           NaN
2012-01-03 22:00:00           NaN
2012-01-03 23:00:00           NaN
2012-01-04 00:00:00    22.1320133
Freq: H, Name: Adj Close, dtype: float64

In [21]:
sample.asfreq('H', method = 'ffill')
# forward fill will take the earlier known value and fill all the missing values with it.

Date
2012-01-03 00:00:00    21.6231384
2012-01-03 01:00:00    21.6231384
2012-01-03 02:00:00    21.6231384
2012-01-03 03:00:00    21.6231384
2012-01-03 04:00:00    21.6231384
2012-01-03 05:00:00    21.6231384
2012-01-03 06:00:00    21.6231384
2012-01-03 07:00:00    21.6231384
2012-01-03 08:00:00    21.6231384
2012-01-03 09:00:00    21.6231384
2012-01-03 10:00:00    21.6231384
2012-01-03 11:00:00    21.6231384
2012-01-03 12:00:00    21.6231384
2012-01-03 13:00:00    21.6231384
2012-01-03 14:00:00    21.6231384
2012-01-03 15:00:00    21.6231384
2012-01-03 16:00:00    21.6231384
2012-01-03 17:00:00    21.6231384
2012-01-03 18:00:00    21.6231384
2012-01-03 19:00:00    21.6231384
2012-01-03 20:00:00    21.6231384
2012-01-03 21:00:00    21.6231384
2012-01-03 22:00:00    21.6231384
2012-01-03 23:00:00    21.6231384
2012-01-04 00:00:00    22.1320133
Freq: H, Name: Adj Close, dtype: float64

In [23]:
sample.asfreq('H', method = 'bfill')
# backward fill will take the next known value and fill the missing values in the backward direction.

Date
2012-01-03 00:00:00    21.6231346
2012-01-03 01:00:00    22.1320076
2012-01-03 02:00:00    22.1320076
2012-01-03 03:00:00    22.1320076
2012-01-03 04:00:00    22.1320076
2012-01-03 05:00:00    22.1320076
2012-01-03 06:00:00    22.1320076
2012-01-03 07:00:00    22.1320076
2012-01-03 08:00:00    22.1320076
2012-01-03 09:00:00    22.1320076
2012-01-03 10:00:00    22.1320076
2012-01-03 11:00:00    22.1320076
2012-01-03 12:00:00    22.1320076
2012-01-03 13:00:00    22.1320076
2012-01-03 14:00:00    22.1320076
2012-01-03 15:00:00    22.1320076
2012-01-03 16:00:00    22.1320076
2012-01-03 17:00:00    22.1320076
2012-01-03 18:00:00    22.1320076
2012-01-03 19:00:00    22.1320076
2012-01-03 20:00:00    22.1320076
2012-01-03 21:00:00    22.1320076
2012-01-03 22:00:00    22.1320076
2012-01-03 23:00:00    22.1320076
2012-01-04 00:00:00    22.1320076
Freq: H, Name: Adj Close, dtype: float64

### Resampling of time-series:

In [ ]:
msftAC / msftAC.shift()
# I haven't confirmed it but i think the default argument for shift is 1 which means to shift prices forward by one day.

In [ ]:
(1 + (msftAC / msftAC.shift() - 1))
# this and immediately above seems to produce the same result. Plus1 and minus1 cancels out so the result is the same as immediately above.

In [22]:
msft_cum_ret = (1 + (msftAC / msftAC.shift() - 1)).cumprod()
msft_cum_ret
# cumprod stands for cummulative product.
# it multiplies the value on 2012-01-04 with the value on 2012-01-05 and produces the product in the index label 2012-01-05. This product 
# can be called cumulative daily return.
# $1 dollar invested on 2012-01-03 has grown to $1.475 on 2013-12-30.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339930
2012-01-06    1.0500561
2012-01-09    1.0362343
                ...
2013-12-23    1.4491994
2013-12-24    1.4674028
2013-12-26    1.4816499
2013-12-27    1.4757139
2013-12-30    1.4757139
Name: Adj Close, Length: 501, dtype: float64

In [23]:
msft_cum_ret['1/1/2012':'1/31/2012']
# note that typing the date in this pattern is the same as typing 2012-01-04 and so on.
# this gives us daily cumulative returns for all the month as explained above.

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339930
2012-01-06    1.0500561
2012-01-09    1.0362343
2012-01-10    1.0399699
2012-01-11    1.0354875
2012-01-12    1.0459469
2012-01-13    1.0552854
2012-01-17    1.0556592
2012-01-18    1.0545385
2012-01-19    1.0504297
2012-01-20    1.1098244
2012-01-23    1.1105714
2012-01-24    1.0960028
2012-01-25    1.1042208
2012-01-26    1.1019797
2012-01-27    1.0918936
2012-01-30    1.1060889
2012-01-31    1.1031003
Name: Adj Close, dtype: float64

In [24]:
msft_cum_ret['1/1/2012':'1/31/2012'].mean()
# mean cumulative return of January 2012. It is a mean of all the daily cumulative returns in January.
# to calculate each month mean cumulative return, we have to write this command 24 times for all 24 months.

1.0686745430400082

In [28]:
msft_cum_ret['1/2012'].mean()
# an alternative to the above method to compute monthly mean.

1.0686745430400082

In [29]:
(msftAC/msftAC.shift()).mean() # mean of daily returns.

1.0008829538514061

In [30]:
msft_cum_ret

Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339930
2012-01-06    1.0500561
2012-01-09    1.0362343
                ...
2013-12-23    1.4491994
2013-12-24    1.4674028
2013-12-26    1.4816499
2013-12-27    1.4757139
2013-12-30    1.4757139
Name: Adj Close, Length: 501, dtype: float64

In [31]:
msft_monthly_cum_ret = msft_cum_ret.resample("M")
msft_monthly_cum_ret
# a better and efficient alternative to the above two methods to compute monthly means.
# does not return a dataframe any longer but an object stored at some location in memory. Nevermind, all the aggregation and interpolation
# can still be validly performed as shown below.

In [32]:
def print_info(groupobject):
    for i, k in groupobject:
        print (i)
        print (k)

In [33]:
print_info(msft_monthly_cum_ret)
# the daily cumulative returns have been grouped by month. In total, we will have 24 groups since we have 24 months.

2012-01-31 00:00:00
Date
2012-01-03          NaN
2012-01-04    1.0235338
2012-01-05    1.0339930
2012-01-06    1.0500561
2012-01-09    1.0362343
2012-01-10    1.0399699
2012-01-11    1.0354875
2012-01-12    1.0459469
2012-01-13    1.0552854
2012-01-17    1.0556592
2012-01-18    1.0545385
2012-01-19    1.0504297
2012-01-20    1.1098244
2012-01-23    1.1105714
2012-01-24    1.0960028
2012-01-25    1.1042208
2012-01-26    1.1019797
2012-01-27    1.0918936
2012-01-30    1.1060889
2012-01-31    1.1031003
Name: Adj Close, dtype: float64
2012-02-29 00:00:00
Date
2012-02-01    1.1165479
2012-02-02    1.1187895
2012-02-03    1.1296225
2012-02-06    1.1281282
2012-02-07    1.1337314
2012-02-08    1.1453117
2012-02-09    1.1494208
2012-02-10    1.1393351
2012-02-13    1.1423234
2012-02-14    1.1374350
2012-02-15    1.1299149
2012-02-16    1.1765404
2012-02-17    1.1750362
2012-02-21    1.1821807
2012-02-22    1.1757880
2012-02-23    1.1795486
2012-02-24    1.1836848
2012-02-27    1.1787966
2012-02-28    1.1983491
2012-02-29    1.1934608
Name: Adj Close, dtype: float64
2012-03-31 00:00:00
Date
2012-03-01    1.2141416
2012-03-02    1.2062452
2012-03-05    1.1957170
2012-03-06    1.1866925
2012-03-07    1.1972208
2012-03-08    1.2036133
2012-03-09    1.2028614
2012-03-12    1.2047414
2012-03-13    1.2284296
2012-03-14    1.2321898
2012-03-15    1.2351981
2012-03-16    1.2257983
2012-03-19    1.2107573
2012-03-20    1.2028614
2012-03-21    1.1998531
2012-03-22    1.2032377
2012-03-23    1.2036133
2012-03-26    1.2254220
2012-03-27    1.2227899
2012-03-28    1.2103814
2012-03-29    1.2077492
2012-03-30    1.2130132
Name: Adj Close, dtype: float64
2012-04-30 00:00:00
Date
2012-04-02    1.2141416
2012-04-03    1.2009814
2012-04-04    1.1735322
2012-04-05    1.1851887
2012-04-09    1.1693961
2012-04-10    1.1457075
2012-04-11    1.1411952
2012-04-12    1.1648840
2012-04-13    1.1584917
2012-04-16    1.1686440
2012-04-17    1.1821807
2012-04-18    1.1709002
2012-04-19    1.1660120
2012-04-20    1.2190298
2012-04-23    1.2077492
2012-04-24    1.2002291
2012-04-25    1.2107573
2012-04-26    1.2073733
2012-04-27    1.2024852
2012-04-30    1.2039891
Name: Adj Close, dtype: float64
2012-05-31 00:00:00
Date
2012-05-01    1.2036133
2012-05-02    1.1957170
2012-05-03    1.1942129
2012-05-04    1.1648840
2012-05-07    1.1524755
2012-05-08    1.1468354
2012-05-09    1.1566121
2012-05-10    1.1558597
2012-05-11    1.1716523
2012-05-14    1.1536038
2012-05-15    1.1433846
2012-05-16    1.1316519
2012-05-17    1.1248389
2012-05-18    1.1078076
2012-05-21    1.1259747
2012-05-22    1.1263531
2012-05-23    1.1017519
2012-05-24    1.1002380
2012-05-25    1.0998595
2012-05-29    1.1187837
2012-05-30    1.1104569
2012-05-31    1.1047800
Name: Adj Close, dtype: float64
2012-06-30 00:00:00
Date
2012-06-01    1.0767723
2012-06-04    1.0805573
2012-06-05    1.0790432
2012-06-06    1.1108360
2012-06-07    1.1062937
2012-06-08    1.1221900
2012-06-11    1.0938043
2012-06-12    1.1085648
2012-06-13    1.1025090
2012-06-14    1.1104569
2012-06-15    1.1361938
2012-06-18    1.1293811
2012-06-19    1.1619305
2012-06-20    1.1706352
2012-06-21    1.1407355
2012-06-22    1.1619305
2012-06-25    1.1305166
2012-06-26    1.1361938
2012-06-27    1.1418707
2012-06-28    1.1320306
2012-06-29    1.1577668
Name: Adj Close, dtype: float64
2012-07-31 00:00:00
Date
2012-07-02    1.1566312
2012-07-03    1.1642010
2012-07-05    1.1619305
2012-07-06    1.1426279
2012-07-09    1.1354368
2012-07-10    1.1255964
2012-07-11    1.1089429
2012-07-12    1.0835847
2012-07-13    1.1123495
2012-07-16    1.1142422
2012-07-17    1.1225684
2012-07-18    1.1524681
2012-07-19    1.1607949
2012-07-20    1.1399783
2012-07-23    1.1081863
2012-07-24    1.1032659
2012-07-25    1.0911546
2012-07-26    1.1036444
2012-07-27    1.1263531
2012-07-30    1.1218115
2012-07-31    1.1153772
Name: Adj Close, dtype: float64
2012-08-31 00:00:00
Date
2012-08-01    1.1131062
2012-08-02    1.1047800
2012-08-03    1.1259747
2012-08-06    1.1335442
2012-08-07    1.1452771
2012-08-08    1.1479267
2012-08-09    1.1543605
2012-08-10    1.1513328
2012-08-13    1.1501973
2012-08-14    1.1479114
2012-08-15    1.1505783
2012-08-16    1.1726757
2012-08-17    1.1772472
2012-08-20    1.1711515
2012-08-21    1.1734374
2012-08-22    1.1635319
2012-08-23    1.1528643
2012-08-24    1.1642936
2012-08-27    1.1692465
2012-08-28    1.1669609
2012-08-29    1.1677226
2012-08-30    1.1551502
2012-08-31    1.1741994
Name: Adj Close, dtype: float64
2012-09-30 00:00:00
Date
2012-09-04    1.1578170
2012-09-05    1.1578170
2012-09-06    1.1943917
2012-09-07    1.1791525
2012-09-10    1.1703894
2012-09-11    1.1730563
2012-09-12    1.1726757
2012-09-13    1.1787710
2012-09-14    1.1890580
2012-09-17    1.1890580
2012-09-18    1.1879152
2012-09-19    1.1829618
2012-09-20    1.1982017
2012-09-21    1.1882961
2012-09-24    1.1726757
2012-09-25    1.1578170
2012-09-26    1.1494354
2012-09-27    1.1490544
2012-09-28    1.1338151
Name: Adj Close, dtype: float64
2012-10-31 00:00:00
Date
2012-10-01    1.1235283
2012-10-02    1.1300052
2012-10-03    1.1376246
2012-10-04    1.1441017
2012-10-05    1.1372438
2012-10-08    1.1345770
2012-10-09    1.1155277
2012-10-10    1.1040981
2012-10-11    1.1029550
2012-10-12    1.1124797
2012-10-15    1.1242902
2012-10-16    1.1235283
2012-10-17    1.1273380
2012-10-18    1.1239092
2012-10-19    1.0911443
2012-10-22    1.0667612
2012-10-23    1.0686664
2012-10-24    1.0629515
2012-10-25    1.0621894
2012-10-26    1.0747620
2012-10-31    1.0873347
Name: Adj Close, dtype: float64
2012-11-30 00:00:00
Date
2012-11-01    1.1246712
2012-11-02    1.1239092
2012-11-05    1.1288620
2012-11-06    1.1376246
2012-11-07    1.1079077
2012-11-08    1.0976215
2012-11-09    1.0983831
2012-11-12    1.0751430
2012-11-13    1.0405725
2012-11-14    1.0309697
2012-11-15    1.0240556
2012-11-16    1.0186776
2012-11-19    1.0267444
2012-11-20    1.0259759
2012-11-21    1.0351949
2012-11-23    1.0640038
2012-11-26    1.0520959
2012-11-27    1.0401883
2012-11-28    1.0509437
2012-11-29    1.0351949
2012-11-30    1.0225189
Name: Adj Close, dtype: float64
2012-12-31 00:00:00
Date
2012-12-03    1.0152208
2012-12-04    1.0129162
2012-12-05    1.0244397
2012-12-06    1.0267444
2012-12-07    1.0163729
2012-12-10    1.0348109
2012-12-11    1.0494072
2012-12-12    1.0463343
2012-12-13    1.0413409
2012-12-14    1.0298176
2012-12-17    1.0409565
2012-12-18    1.0586259
2012-12-19    1.0490232
2012-12-20    1.0632354
2012-12-21    1.0544008
2012-12-24    1.0394200
2012-12-26    1.0317378
2012-12-27    1.0355790
2012-12-28    1.0198301
2012-12-31    1.0259759
Name: Adj Close, dtype: float64
2013-01-31 00:00:00
Date
2013-01-02    1.0609306
2013-01-03    1.0467184
2013-01-04    1.0271285
2013-01-07    1.0252080
2013-01-08    1.0198301
2013-01-09    1.0255921
2013-01-10    1.0163729
2013-01-11    1.0305855
2013-01-14    1.0328904
2013-01-15    1.0451820
2013-01-16    1.0386519
2013-01-17    1.0467184
2013-01-18    1.0467184
2013-01-22    1.0428773
2013-01-23    1.0605467
2013-01-24    1.0613151
2013-01-25    1.0709177
2013-01-28    1.0720702
2013-01-29    1.0759112
2013-01-30    1.0697653
2013-01-31    1.0544008
Name: Adj Close, dtype: float64
2013-02-28 00:00:00
Date
2013-02-01    1.0728382
2013-02-04    1.0540166
2013-02-05    1.0563213
2013-02-06    1.0501757
2013-02-07    1.0478710
2013-02-08    1.0582417
2013-02-11    1.0701496
2013-02-12    1.0709177
2013-02-13    1.0766795
2013-02-14    1.0770638
2013-02-15    1.0759112
2013-02-19    1.0863683
2013-02-20    1.0793973
2013-02-21    1.0646798
2013-02-22    1.0751365
2013-02-25    1.0600321
2013-02-26    1.0600321
2013-02-27    1.0770731
2013-02-28    1.0766860
Name: Adj Close, dtype: float64
2013-03-31 00:00:00
Date
2013-03-01    1.0824955
2013-03-04    1.0902410
2013-03-05    1.0979871
2013-03-06    1.0879172
2013-03-07    1.0898537
2013-03-08    1.0844321
2013-03-11    1.0793973
2013-03-12    1.0809462
2013-03-13    1.0813336
2013-03-14    1.0898537
2013-03-15    1.0859812
2013-03-18    1.0883047
2013-03-19    1.0914031
2013-03-20    1.0968255
2013-03-21    1.0886921
2013-03-22    1.0941143
2013-03-25    1.0906285
2013-03-26    1.0906285
2013-03-27    1.0987619
2013-03-28    1.1080570
Name: Adj Close, dtype: float64
2013-04-30 00:00:00
Date
2013-04-01    1.1080570
2013-04-02    1.1154155
2013-04-03    1.1061209
2013-04-04    1.1076694
2013-04-05    1.1115425
2013-04-08    1.1072823
2013-04-09    1.1467866
2013-04-10    1.1727357
2013-04-11    1.1208377
2013-04-12    1.1150284
2013-04-15    1.1111555
2013-04-16    1.1219997
2013-04-17    1.1165776
2013-04-18    1.1150284
2013-04-19    1.1529836
2013-04-22    1.1940371
2013-04-23    1.1851290
2013-04-24    1.2300554
2013-04-25    1.2370270
2013-04-26    1.2312175
2013-04-29    1.2629754
2013-04-30    1.2819533
Name: Adj Close, dtype: float64
2013-05-31 00:00:00
Date
2013-05-01    1.2672362
2013-05-02    1.2842769
2013-05-03    1.2970579
2013-05-06    1.3071278
2013-05-07    1.2900868
2013-05-08    1.2776931
2013-05-09    1.2649125
2013-05-10    1.2660743
2013-05-13    1.2792423
2013-05-14    1.3077131
2013-05-15    1.3201938
2013-05-16    1.3291639
2013-05-17    1.3599751
2013-05-20    1.3681652
2013-05-21    1.3591951
2013-05-22    1.3498347
2013-05-23    1.3318941
2013-05-24    1.3365744
2013-05-28    1.3658250
2013-05-29    1.3603651
2013-05-30    1.3662153
2013-05-31    1.3611450
Name: Adj Close, dtype: float64
2013-06-30 00:00:00
Date
2013-06-03    1.3880561
2013-06-04    1.3646551
2013-06-05    1.3564645
2013-06-06    1.3634852
2013-06-07    1.3911757
2013-06-10    1.3833757
2013-06-11    1.3588046
2013-06-12    1.3650449
2013-06-13    1.3541251
2013-06-14    1.3416444
2013-06-17    1.3650449
2013-06-18    1.3642655
2013-06-19    1.3490549
2013-06-20    1.3061534
2013-06-21    1.2975730
2013-06-24    1.3151234
2013-06-25    1.3131732
2013-06-26    1.3396942
2013-06-27    1.3502246
2013-06-28    1.3471044
Name: Adj Close, dtype: float64
2013-07-31 00:00:00
Date
2013-07-01    1.3400845
2013-07-02    1.3237035
2013-07-03    1.3264339
2013-07-05    1.3342344
2013-07-08    1.3389142
2013-07-09    1.3396942
2013-07-10    1.3533449
2013-07-11    1.3919563
2013-07-12    1.3911757
2013-07-15    1.4106760
2013-07-16    1.4145767
2013-07-17    1.3939061
2013-07-18    1.3822059
2013-07-19    1.2246404
2013-07-22    1.2484310
2013-07-23    1.2410209
2013-07-24    1.2464812
2013-07-25    1.2242504
2013-07-26    1.2332209
2013-07-29    1.2301007
2013-07-30    1.2421907
2013-07-31    1.2418011
Name: Adj Close, dtype: float64
2013-08-31 00:00:00
Date
2013-08-01    1.2351707
2013-08-02    1.2437512
2013-08-05    1.2363410
2013-08-06    1.2316606
2013-08-07    1.2503815
2013-08-08    1.2827521
2013-08-09    1.2753424
2013-08-12    1.2819722
2013-08-13    1.2658693
2013-08-14    1.2705823
2013-08-15    1.2485875
2013-08-16    1.2489805
2013-08-19    1.2328772
2013-08-20    1.2419108
2013-08-21    1.2415180
2013-08-22    1.2721535
2013-08-23    1.3648448
2013-08-26    1.3412794
2013-08-27    1.3063233
2013-08-28    1.2968976
2013-08-29    1.3177136
2013-08-30    1.3118223
Name: Adj Close, dtype: float64
2013-09-30 00:00:00
Date
2013-09-03    1.2521226
2013-09-04    1.2254150
2013-09-05    1.2265930
2013-09-06    1.2234511
2013-09-09    1.2434817
2013-09-10    1.2721535
2013-09-11    1.2859001
2013-09-12    1.2839364
2013-09-13    1.2972900
2013-09-16    1.2882566
2013-09-17    1.2933626
2013-09-18    1.3086803
2013-09-19    1.3212487
2013-09-20    1.2878643
2013-09-23    1.2859001
2013-09-24    1.2745101
2013-09-25    1.2768662
2013-09-26    1.2870784
2013-09-27    1.3067165
2013-09-30    1.3071092
Name: Adj Close, dtype: float64
2013-10-31 00:00:00
Date
2013-10-01    1.3188919
2013-10-02    1.3322454
2013-10-03    1.3298893
2013-10-04    1.3306750
2013-10-07    1.3078945
2013-10-08    1.2965045
2013-10-09    1.2988610
2013-10-10    1.3259616
2013-10-11    1.3404936
2013-10-14    1.3530621
2013-10-15    1.3546332
2013-10-16    1.3605246
2013-10-17    1.3715219
2013-10-18    1.3730932
2013-10-21    1.3742713
2013-10-22    1.3581678
2013-10-23    1.3259616
2013-10-24    1.3243905
2013-10-25    1.4033360
2013-10-28    1.3970513
2013-10-29    1.3950878
2013-10-30    1.3958734
2013-10-31    1.3907674
Name: Adj Close, dtype: float64
2013-11-30 00:00:00
Date
2013-11-01    1.3954805
2013-11-04    1.4115836
2013-11-05    1.4390768
2013-11-06    1.4995620
2013-11-07    1.4728547
2013-11-08    1.4838513
2013-11-11    1.4763892
2013-11-12    1.4673556
2013-11-13    1.4987771
2013-11-14    1.4932781
2013-11-15    1.4862084
2013-11-18    1.4610711
2013-11-19    1.4539481
2013-11-20    1.4674028
2013-11-21    1.4800670
2013-11-22    1.4867946
2013-11-25    1.4895649
2013-11-26    1.4780881
2013-11-27    1.4879817
2013-11-29    1.5089560
Name: Adj Close, dtype: float64
2013-12-31 00:00:00
Date
2013-12-02    1.5216198
2013-12-03    1.5160790
2013-12-04    1.5410109
2013-12-05    1.5038115
2013-12-06    1.5180586
2013-12-09    1.5319091
2013-12-10    1.5081646
2013-12-11    1.4883774
2013-12-12    1.4729436
2013-12-13    1.4519694
2013-12-16    1.4598845
2013-12-17    1.4452416
2013-12-18    1.4476164
2013-12-19    1.4345569
2013-12-20    1.4563225
2013-12-23    1.4491994
2013-12-24    1.4674028
2013-12-26    1.4816499
2013-12-27    1.4757139
2013-12-30    1.4757139
Name: Adj Close, dtype: float64

In [34]:
len(msft_monthly_cum_ret)
# 24 groups confirmed.

24

In [35]:
msft_monthly_cum_ret.size()
# size of each group.

Date
2012-01-31    20
2012-02-29    20
2012-03-31    22
2012-04-30    20
2012-05-31    22
2012-06-30    21
2012-07-31    21
2012-08-31    23
2012-09-30    19
2012-10-31    21
2012-11-30    21
2012-12-31    20
2013-01-31    21
2013-02-28    19
2013-03-31    20
2013-04-30    22
2013-05-31    22
2013-06-30    20
2013-07-31    22
2013-08-31    22
2013-09-30    20
2013-10-31    23
2013-11-30    20
2013-12-31    20
Freq: M, Name: Adj Close, dtype: int64

In [36]:
msft_monthly_cum_ret.mean()

Date
2012-01-31    1.0686745
2012-02-29    1.1556973
2012-03-31    1.2105694
2012-04-30    1.1846434
2012-05-31    1.1405158
2012-06-30    1.1233435
2012-07-31    1.1262450
2012-08-31    1.1536292
2012-09-30    1.1727557
2012-10-31    1.1073817
2012-11-30    1.0648218
2012-12-31    1.0358095
2013-01-31    1.0462063
2013-02-28    1.0678732
2013-03-31    1.0898927
2013-04-30    1.1568916
2013-05-31    1.3204531
2013-06-30    1.3507122
2013-07-31    1.3124111
2013-08-31    1.2726696
2013-09-30    1.2773968
2013-10-31    1.3503982
2013-11-30    1.4719146
2013-12-31    1.4823623
Freq: M, Name: Adj Close, dtype: float64

In [37]:
msft_cum_ret['2/2012'].mean()
# to compare and confirm the mean of feb in immediately above series. Confirmed and the same.

1.155697279961669

In [38]:
## The above work is almost the end of page 94 in the book. After that, for about 3 pages, the discussion in the book cannot be
# implemented here since there is change in the newer version of pandas. But what we can do something extra and interesting follows
# as:

In [39]:
msft

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-03,26.9599991,26.3899994,26.5499992,26.7700005,64731500.0,21.6231384
2012-01-04,27.4699993,26.7800007,26.8199997,27.3999996,80516100.0,22.1320133
2012-01-05,27.7299995,27.2900009,27.3799992,27.6800003,56081400.0,22.3581734
2012-01-06,28.1900005,27.5300007,27.5300007,28.1100006,99455500.0,22.7055092
2012-01-09,28.1000004,27.7199993,28.0499992,27.7399998,59706800.0,22.4066372
...,...,...,...,...,...,...
2013-12-23,36.8899994,36.5499992,36.8100014,36.6199989,25128700.0,31.3362389
2013-12-24,37.1699982,36.6399994,36.7200012,37.0800018,14243000.0,31.7298546
2013-12-26,37.4900017,37.1699982,37.2000008,37.4399986,17612800.0,32.0379219
2013-12-27,37.6199989,37.1699982,37.5800018,37.2900009,14563000.0,31.9095650
2013-12-30,37.3800011,36.9000015,37.2200012,37.2900009,16290500.0,31.9095650

In [40]:
msft_resample = msft.resample('M')
# the frequency has been changed to Monthly from Daily.

In [41]:
msft_resample

In [42]:
for i, k in msft_resample:
    print(i)
    print(k)
# the data has been grouped on monthly basis into 24 groups since we have 24 months.

2012-01-31 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-01-03  26.9599991  26.3899994  26.5499992  26.7700005   64731500.0
2012-01-04  27.4699993  26.7800007  26.8199997  27.3999996   80516100.0
2012-01-05  27.7299995  27.2900009  27.3799992  27.6800003   56081400.0
2012-01-06  28.1900005  27.5300007  27.5300007  28.1100006   99455500.0
2012-01-09  28.1000004  27.7199993  28.0499992  27.7399998   59706800.0
2012-01-10  28.1499996  27.7500000  27.9300003  27.8400002   60014400.0
2012-01-11  27.9799995  27.3700008  27.4300003  27.7199993   65582400.0
2012-01-12  28.0200005  27.6499996  27.8700008  28.0000000   49370800.0
2012-01-13  28.2500000  27.7900009  27.9300003  28.2500000   60196100.0
2012-01-17  28.6499996  28.1700001  28.3999996  28.2600002   72395300.0
2012-01-18  28.3999996  27.9699993  28.3099995  28.2299995   64860600.0
2012-01-19  28.4400005  28.0300007  28.1599998  28.1200008   74053500.0
2012-01-20  29.7399998  28.7500000  28.8199997  29.7099991  165902900.0
2012-01-23  29.9500008  29.3500004  29.5499992  29.7299995   76078100.0
2012-01-24  29.5699997  29.1800003  29.4699993  29.3400002   51703300.0
2012-01-25  29.6499996  29.0699997  29.0699997  29.5599995   59231700.0
2012-01-26  29.7000008  29.3999996  29.6100006  29.5000000   49102800.0
2012-01-27  29.5300007  29.1700001  29.4500008  29.2299995   44187700.0
2012-01-30  29.6200008  28.8299999  28.9699993  29.6100006   51114800.0
2012-01-31  29.7000008  29.2299995  29.6599998  29.5300007   50572400.0

             Adj Close
Date
2012-01-03  21.6231384
2012-01-04  22.1320133
2012-01-05  22.3581734
2012-01-06  22.7055092
2012-01-09  22.4066372
2012-01-10  22.4874134
2012-01-11  22.3904896
2012-01-12  22.6166553
2012-01-13  22.8185825
2012-01-17  22.8266640
2012-01-18  22.8024330
2012-01-19  22.7135868
2012-01-20  23.9978867
2012-01-23  24.0140381
2012-01-24  23.6990204
2012-01-25  23.8767185
2012-01-26  23.8282604
2012-01-27  23.6101665
2012-01-30  23.9171143
2012-01-31  23.8524914
2012-02-29 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-02-01  30.0499992  29.7600002  29.7900009  29.8899994  67409900.0
2012-02-02  30.1700001  29.7099991  29.8999996  29.9500008  52223300.0
2012-02-03  30.3999996  30.0900002  30.1399994  30.2399998  41838500.0
2012-02-06  30.2199993  29.9699993  30.0400009  30.2000008  28039700.0
2012-02-07  30.4899998  30.0499992  30.1499996  30.3500004  39242400.0
2012-02-08  30.6700001  30.2199993  30.2600002  30.6599998  49659100.0
2012-02-09  30.7999992  30.4799995  30.6800003  30.7700005  50481600.0
2012-02-10  30.7999992  30.3600006  30.6399994  30.5000000  44605300.0
2012-02-13  30.7700005  30.4300003  30.6299992  30.5799999  33319800.0
2012-02-14  30.4599991  29.8500004  30.3299999  30.2500000  59644000.0
2012-02-15  30.3899994  30.0300007  30.3299999  30.0499992  43311300.0
2012-02-16  31.5499992  30.2999992  30.3099995  31.2900009  94705100.0
2012-02-17  31.3199997  30.9500008  31.2000008  31.2500000  70036500.0
2012-02-21  31.6100006  31.1499996  31.1800003  31.4400005  50829900.0
2012-02-22  31.6800003  31.1800003  31.4500008  31.2700005  49253200.0
2012-02-23  31.5900002  31.0000000  31.2000008  31.3700008  35034700.0
2012-02-24  31.5000000  31.2399998  31.4799995  31.4799995  35575400.0
2012-02-27  31.5000000  31.1000004  31.2399998  31.3500004  34568400.0
2012-02-28  31.9300003  31.3799992  31.4099998  31.8700008  45230600.0
2012-02-29  32.0000000  31.6100006  31.8899994  31.7399998  59323600.0

             Adj Close
Date
2012-02-01  24.1432705
2012-02-02  24.1917400
2012-02-03  24.4259834
2012-02-06  24.3936729
2012-02-07  24.5148315
2012-02-08  24.7652340
2012-02-09  24.8540859
2012-02-10  24.6359997
2012-02-13  24.7006168
2012-02-14  24.5949135
2012-02-15  24.4323063
2012-02-16  25.4404964
2012-02-17  25.4079704
2012-02-21  25.5624561
2012-02-22  25.4242268
2012-02-23  25.5055428
2012-02-24  25.5949802
2012-02-27  25.4892826
2012-02-28  25.9120674
2012-02-29  25.8063679
2012-03-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-03-01  32.3899994  31.8500004  31.9300003  32.2900009  77344100.0
2012-03-02  32.4399986  32.0000000  32.3100014  32.0800018  47314200.0
2012-03-05  32.0499992  31.6200008  32.0099983  31.7999992  45240000.0
2012-03-06  31.9799995  31.4899998  31.5400009  31.5599995  51932900.0
2012-03-07  31.9200001  31.5300007  31.6700001  31.8400002  34340400.0
2012-03-08  32.2099991  31.8999996  32.0400009  32.0099983  36747400.0
2012-03-09  32.1599998  31.9200001  32.0999985  31.9899998  34628400.0
2012-03-12  32.2000008  31.8199997  31.9699993  32.0400009  34073600.0
2012-03-13  32.6899986  32.1500015  32.2400017  32.6699982  48951700.0
2012-03-14  32.8800011  32.4900017  32.5299988  32.7700005  41986900.0
2012-03-15  32.9399986  32.5800018  32.7900009  32.8499985  49068300.0
2012-03-16  32.9500008  32.5000000  32.9099998  32.5999985  65626400.0
2012-03-19  32.6100006  32.1500015  32.5400009  32.2000008  44789200.0
2012-03-20  32.1500015  31.7399998  32.0999985  31.9899998  41566800.0
2012-03-21  32.1500015  31.8199997  31.9599991  31.9099998  37928600.0
2012-03-22  32.0900002  31.7900009  31.8099995  32.0000000  31749500.0
2012-03-23  32.1100006  31.7199993  32.0999985  32.0099983  35912200.0
2012-03-26  32.6100006  32.1500015  32.1899986  32.5900002  36758300.0
2012-03-27  32.7000008  32.4000015  32.6500015  32.5200005  36274900.0
2012-03-28  32.7000008  32.0400009  32.5200005  32.1899986  41344800.0
2012-03-29  32.1899986  31.8099995  32.0600014  32.1199989  37038500.0
2012-03-30  32.4099998  32.0400009  32.4000015  32.2599983  31749400.0

             Adj Close
Date
2012-03-01  26.2535515
2012-03-02  26.0828075
2012-03-05  25.8551540
2012-03-06  25.6600170
2012-03-07  25.8876705
2012-03-08  26.0258961
2012-03-09  26.0096378
2012-03-12  26.0502892
2012-03-13  26.5625038
2012-03-14  26.6438103
2012-03-15  26.7088585
2012-03-16  26.5056057
2012-03-19  26.1803722
2012-03-20  26.0096378
2012-03-21  25.9445896
2012-03-22  26.0177746
2012-03-23  26.0258961
2012-03-26  26.4974689
2012-03-27  26.4405556
2012-03-28  26.1722450
2012-03-29  26.1153278
2012-03-30  26.2291527
2012-04-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-04-02  32.4599991  31.9500008  32.2200012  32.2900009   35853600.0
2012-04-03  32.1899986  31.6599998  32.1599998  31.9400005   42752100.0
2012-04-04  31.6900005  31.0499992  31.6599998  31.2099991   49455900.0
2012-04-05  31.6299992  31.0499992  31.1499996  31.5200005   50368600.0
2012-04-09  31.3999996  30.9699993  31.2199993  31.1000004   31056400.0
2012-04-10  31.1900005  30.2999992  31.0599995  30.4699993   54131300.0
2012-04-11  30.5300007  30.2299995  30.4300003  30.3500004   43014000.0
2012-04-12  31.0400009  30.4200001  30.4799995  30.9799995   38304000.0
2012-04-13  31.1599998  30.7199993  30.8899994  30.8099995   39749200.0
2012-04-16  31.1900005  30.7700005  30.9899998  31.0799999   38124800.0
2012-04-17  31.6100006  31.2000008  31.2700005  31.4400005   34361500.0
2012-04-18  31.3099995  31.0400009  31.2800007  31.1399994   40552900.0
2012-04-19  31.6800003  30.9400005  31.1299992  31.0100002   54781200.0
2012-04-20  32.8899994  32.0499992  32.1500015  32.4199982  106045000.0
2012-04-23  32.5000000  32.0299988  32.3100014  32.1199989   61398200.0
2012-04-24  32.5200005  31.8299999  32.2099991  31.9200001   40871100.0
2012-04-25  32.3199997  31.8700008  31.9200001  32.2000008   62495500.0
2012-04-26  32.2299995  31.9200001  32.1199989  32.1100006   40308100.0
2012-04-27  32.2200012  31.8799992  32.1199989  31.9799995   41419100.0
2012-04-30  32.1100006  31.9200001  31.9799995  32.0200005   35697200.0

             Adj Close
Date
2012-04-02  26.2535515
2012-04-03  25.9689865
2012-04-04  25.3754482
2012-04-05  25.6274986
2012-04-09  25.2860146
2012-04-10  24.7737923
2012-04-11  24.6762218
2012-04-12  25.1884480
2012-04-13  25.0502262
2012-04-16  25.2697506
2012-04-17  25.5624561
2012-04-18  25.3185368
2012-04-19  25.2128391
2012-04-20  26.3592510
2012-04-23  26.1153278
2012-04-24  25.9527206
2012-04-25  26.1803722
2012-04-26  26.1072006
2012-04-27  26.0015049
2012-04-30  26.0340233
2012-05-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-05-01  32.3400002  31.9500008  32.0499992  32.0099983  43832300.0
2012-05-02  31.9300003  31.6399994  31.8500004  31.7999992  37385300.0
2012-05-03  31.8999996  31.6100006  31.8799992  31.7600002  31501300.0
2012-05-04  31.5699997  30.9200001  31.4500008  30.9799995  57927200.0
2012-05-07  30.8600006  30.5699997  30.7000008  30.6499996  48641400.0
2012-05-08  30.7800007  30.1700001  30.4799995  30.5000000  46328300.0
2012-05-09  30.8299999  30.1000004  30.1900005  30.7600002  50309300.0
2012-05-10  31.0200005  30.4500008  30.8600006  30.7399998  43839200.0
2012-05-11  31.5400009  30.6900005  30.6900005  31.1599998  43459300.0
2012-05-14  31.0400009  30.6399994  30.8199997  30.6800003  40528900.0
2012-05-15  30.7999992  30.1499996  30.6399994  30.2099991  61822800.0
2012-05-16  30.3199997  29.7399998  30.3099995  29.8999996  60083700.0
2012-05-17  30.2099991  29.7099991  29.9899998  29.7199993  48484000.0
2012-05-18  29.8099995  29.1700001  29.7900009  29.2700005  56205300.0
2012-05-21  29.7900009  29.0599995  29.1000004  29.7500000  38787900.0
2012-05-22  29.8799992  29.5000000  29.6900005  29.7600002  39504900.0
2012-05-23  29.3999996  28.6399994  29.3500004  29.1100006  65171000.0
2012-05-24  29.2999992  28.7600002  29.1599998  29.0699997  52575000.0
2012-05-25  29.3600006  29.0100002  29.2000008  29.0599995  29507200.0
2012-05-29  29.7199993  29.2199993  29.3799992  29.5599995  37758800.0
2012-05-30  29.4799995  29.1200008  29.3500004  29.3400002  41585500.0
2012-05-31  29.4200001  28.9400005  29.2999992  29.1900005  39134000.0

             Adj Close
Date
2012-05-01  26.0258961
2012-05-02  25.8551540
2012-05-03  25.8226299
2012-05-04  25.1884480
2012-05-07  24.9201374
2012-05-08  24.7981815
2012-05-09  25.0095825
2012-05-10  24.9933147
2012-05-11  25.3347988
2012-05-14  24.9445343
2012-05-15  24.7235641
2012-05-16  24.4698658
2012-05-17  24.3225479
2012-05-18  23.9542770
2012-05-21  24.3471069
2012-05-22  24.3552895
2012-05-23  23.8233337
2012-05-24  23.7905979
2012-05-25  23.7824135
2012-05-29  24.1916142
2012-05-30  24.0115643
2012-05-31  23.8888111
2012-06-30 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-06-01  28.9599991  28.4400005  28.7600002  28.4500008  56634300.0
2012-06-04  28.7800007  28.3199997  28.6200008  28.5499992  47926300.0
2012-06-05  28.7500000  28.3899994  28.5100002  28.5100002  45715400.0
2012-06-06  29.3700008  28.8099995  28.8799992  29.3500004  46860500.0
2012-06-07  29.7000008  29.1700001  29.6399994  29.2299995  37792800.0
2012-06-08  29.6800003  29.0499992  29.2099991  29.6499996  42551100.0
2012-06-11  29.8099995  28.8199997  29.7299995  28.8999996  46361900.0
2012-06-12  29.2999992  28.8400002  29.1000004  29.2900009  35337900.0
2012-06-13  29.4400005  29.0499992  29.2199993  29.1299992  32984600.0
2012-06-14  29.4599991  28.8799992  29.3299999  29.3400002  39458900.0
2012-06-15  30.0799999  29.4899998  29.5900002  30.0200005  62314400.0
2012-06-18  30.0300007  29.7099991  29.9899998  29.8400002  58679900.0
2012-06-19  31.1100006  30.0499992  30.1900005  30.7000008  75725800.0
2012-06-20  31.0499992  30.6399994  30.9300003  30.9300003  36257100.0
2012-06-21  31.1399994  30.0599995  30.9599991  30.1399994  48456600.0
2012-06-22  30.7299995  30.0300007  30.2999992  30.7000008  45098100.0
2012-06-25  30.3199997  29.6200008  30.2999992  29.8700008  42217200.0
2012-06-26  30.2700005  29.9400005  30.0000000  30.0200005  38421300.0
2012-06-27  30.5000000  30.0300007  30.1900005  30.1700001  33781700.0
2012-06-28  30.0499992  29.4200001  29.9799995  29.9099998  45328400.0
2012-06-29  30.6900005  30.1399994  30.4500008  30.5900002  55227200.0

             Adj Close
Date
2012-06-01  23.2831974
2012-06-04  23.3650398
2012-06-05  23.3323002
2012-06-06  24.0197601
2012-06-07  23.9215412
2012-06-08  24.2652702
2012-06-11  23.6514816
2012-06-12  23.9706497
2012-06-13  23.8397045
2012-06-14  24.0115643
2012-06-15  24.5680752
2012-06-18  24.4207649
2012-06-19  25.1245842
2012-06-20  25.3128071
2012-06-21  24.6662827
2012-06-22  25.1245842
2012-06-25  24.4453163
2012-06-26  24.5680752
2012-06-27  24.6908283
2012-06-28  24.4780540
2012-06-29  25.0345516
2012-07-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-07-02  30.6200008  30.2099991  30.6200008  30.5599995  30589100.0
2012-07-03  30.7600002  30.1700001  30.2299995  30.7600002  20938100.0
2012-07-05  30.7800007  30.3799992  30.5900002  30.7000008  28801900.0
2012-07-06  30.7000008  29.9500008  30.6100006  30.1900005  38294800.0
2012-07-09  30.2299995  29.7800007  30.1200008  30.0000000  30680800.0
2012-07-10  30.2199993  29.5100002  30.0799999  29.7399998  37534100.0
2012-07-11  29.7399998  29.1100006  29.7099991  29.2999992  39184900.0
2012-07-12  29.1800003  28.5400009  29.1499996  28.6299992  63523600.0
2012-07-13  29.4799995  28.7199993  28.7600002  29.3899994  39085000.0
2012-07-16  29.5300007  29.0400009  29.4799995  29.4400005  27900600.0
2012-07-17  29.8600006  29.2000008  29.6399994  29.6599998  33771300.0
2012-07-18  30.4500008  29.4599991  29.6000004  30.4500008  41090400.0
2012-07-19  30.7999992  30.3799992  30.5100002  30.6700001  46663200.0
2012-07-20  31.0499992  30.0499992  31.0000000  30.1200008  64021700.0
2012-07-23  29.5799999  29.0100002  29.5699997  29.2800007  55151900.0
2012-07-24  29.3600006  28.8999996  29.2399998  29.1499996  47723300.0
2012-07-25  29.3299999  28.7800007  29.2399998  28.8299999  45579500.0
2012-07-26  29.5000000  29.0900002  29.2299995  29.1599998  45301400.0
2012-07-27  29.8500004  29.1800003  29.4799995  29.7600002  44242600.0
2012-07-30  29.8199997  29.4599991  29.7500000  29.6399994  28905000.0
2012-07-31  29.7099991  29.3299999  29.4799995  29.4699993  37620900.0

             Adj Close
Date
2012-07-02  25.0099964
2012-07-03  25.1736794
2012-07-05  25.1245842
2012-07-06  24.7072010
2012-07-09  24.5517063
2012-07-10  24.3389263
2012-07-11  23.9788265
2012-07-12  23.4305019
2012-07-13  24.0524864
2012-07-16  24.0934124
2012-07-17  24.2734528
2012-07-18  24.9199772
2012-07-19  25.1000290
2012-07-20  24.6499081
2012-07-23  23.9624653
2012-07-24  23.8560715
2012-07-25  23.5941868
2012-07-26  23.8642559
2012-07-27  24.3552895
2012-07-30  24.2570858
2012-07-31  24.1179562
2012-08-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-08-01  29.6499996  29.2099991  29.5900002  29.4099998  31721800.0
2012-08-02  29.5300007  28.9699993  29.2099991  29.1900005  39520500.0
2012-08-03  29.9400005  29.4799995  29.5300007  29.7500000  35859400.0
2012-08-06  30.1100006  29.8099995  30.0000000  29.9500008  27471800.0
2012-08-07  30.3500004  29.8700008  30.0699997  30.2600002  28002900.0
2012-08-08  30.4699993  30.1100006  30.2099991  30.3299999  26257600.0
2012-08-09  30.6499996  30.2999992  30.3899994  30.5000000  24920800.0
2012-08-10  30.6200008  30.2500000  30.5000000  30.4200001  27810300.0
2012-08-13  30.4599991  30.1599998  30.3500004  30.3899994  23049100.0
2012-08-14  30.3899994  30.0100002  30.2999992  30.1299992  34551400.0
2012-08-15  30.2800007  30.0200005  30.1100006  30.2000008  24351000.0
2012-08-16  30.9400005  30.2600002  30.3600006  30.7800007  35787200.0
2012-08-17  30.9200001  30.5900002  30.9200001  30.8999996  32589900.0
2012-08-20  30.8500004  30.5799999  30.8199997  30.7399998  23737700.0
2012-08-21  30.9599991  30.6100006  30.7600002  30.7999992  28822700.0
2012-08-22  30.7600002  30.4699993  30.5900002  30.5400009  33437400.0
2012-08-23  30.3999996  30.0799999  30.3899994  30.2600002  28355600.0
2012-08-24  30.6299992  30.1800003  30.2500000  30.5599995  22943300.0
2012-08-27  30.9599991  30.5900002  30.9300003  30.6900005  34691100.0
2012-08-28  30.7999992  30.5200005  30.7000008  30.6299992  23947900.0
2012-08-29  30.7500000  30.4400005  30.6499996  30.6499996  23346800.0
2012-08-30  30.6100006  30.2199993  30.5300007  30.3199997  23982100.0
2012-08-31  30.9599991  30.3799992  30.6000004  30.8199997  36590100.0

             Adj Close
Date
2012-08-01  24.0688496
2012-08-02  23.8888111
2012-08-03  24.3471069
2012-08-06  24.5107841
2012-08-07  24.7644844
2012-08-08  24.8217773
2012-08-09  24.9608974
2012-08-10  24.8954277
2012-08-13  24.8708744
2012-08-14  24.8214474
2012-08-15  24.8791142
2012-08-16  25.3569298
2012-08-17  25.4557800
2012-08-20  25.3239708
2012-08-21  25.3733997
2012-08-22  25.1592121
2012-08-23  24.9285450
2012-08-24  25.1756821
2012-08-27  25.2827797
2012-08-28  25.2333565
2012-08-29  25.2498283
2012-08-30  24.9779720
2012-08-31  25.3898754
2012-09-30 00:00:00
                  High         Low        Open       Close       Volume  \
Date
2012-09-04  30.6599998  30.1499996  30.4500008  30.3899994   48556700.0
2012-09-05  30.5300007  30.2099991  30.2199993  30.3899994   33650000.0
2012-09-06  31.3600006  30.4599991  30.5000000  31.3500004   48371700.0
2012-09-07  31.0699997  30.7299995  31.0400009  30.9500008   42649100.0
2012-09-10  30.8999996  30.5100002  30.8299999  30.7199993   40524000.0
2012-09-11  30.9099998  30.6100006  30.6900005  30.7900009   25191800.0
2012-09-12  31.1800003  30.7299995  30.9400005  30.7800007   32775800.0
2012-09-13  31.1800003  30.3999996  30.8899994  30.9400005   45047300.0
2012-09-14  31.2500000  30.8099995  31.0100002  31.2099991   51422800.0
2012-09-17  31.2600002  31.0400009  31.1900005  31.2099991   36488500.0
2012-09-18  31.2099991  31.0300007  31.1000004  31.1800003   34542700.0
2012-09-19  31.1900005  31.0400009  31.0900002  31.0499992   48871900.0
2012-09-20  31.4799995  30.9099998  30.9500008  31.4500008   45543000.0
2012-09-21  31.6100006  31.0900002  31.4300003  31.1900005  102348900.0
2012-09-24  31.0699997  30.6399994  31.0000000  30.7800007   46825900.0
2012-09-25  31.0000000  30.3600006  30.9500008  30.3899994   54266400.0
2012-09-26  30.6000004  30.0400009  30.2800007  30.1700001   54672000.0
2012-09-27  30.3999996  29.8899994  30.1700001  30.1599998   47129900.0
2012-09-28  30.2600002  29.7399998  30.1800003  29.7600002   54229300.0

             Adj Close
Date
2012-09-04  25.0356369
2012-09-05  25.0356369
2012-09-06  25.8264980
2012-09-07  25.4969788
2012-09-10  25.3074913
2012-09-11  25.3651581
2012-09-12  25.3569298
2012-09-13  25.4887295
2012-09-14  25.7111664
2012-09-17  25.7111664
2012-09-18  25.6864548
2012-09-19  25.5793476
2012-09-20  25.9088802
2012-09-21  25.6946907
2012-09-24  25.3569298
2012-09-25  25.0356369
2012-09-26  24.8544006
2012-09-27  24.8461628
2012-09-28  24.5166416
2012-10-31 00:00:00
                  High         Low        Open       Close      Volume  \
Date
2012-10-01  29.9799995  29.4200001  29.8099995  29.4899998  54042700.0
2012-10-02  29.8899994  29.5000000  29.6800003  29.6599998  43338900.0
2012-10-03  29.9899998  29.6700001  29.7500000  29.8600006  46655900.0
2012-10-04  30.0300007  29.5699997  29.9699993  30.0300007  43634900.0
2012-10-05  30.2500000  29.7399998  30.2299995  29.8500004  41133900.0
2012-10-08  29.9200001  29.5499992  29.6399994  29.7800007  29752000.0
2012-10-09  29.7399998  29.1800003  29.6800003  29.2800007  45121100.0
2012-10-10  29.3099995  28.9500008  29.1499996  28.9799995  47227100.0
2012-10-11  29.2500000  28.8700008  29.2199993  28.9500008  41488500.0
2012-10-12  29.3199997  28.7999992  28.9699993  29.2000008  46464700.0
2012-10-15  29.7199993  29.2500000  29.3700008  29.5100002  42440200.0
2012-10-16  29.7399998  29.3199997  29.4500008  29.4899998  47739400.0
2012-10-17  29.6399994  29.0900002  29.2999992  29.5900002  44206100.0
2012-10-18  29.7299995  29.2600002  29.6499996  29.5000000  59238500.0

In [45]:
msft_resample.mean()
# mean of high, low, open, close, volume and adj close for each month.

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2012-01-31,28.6900001,28.1710001,28.3479999,28.5165000,6.7742905e+07,23.0338496
2012-02-29,30.9949998,30.5429999,30.7125000,30.8250002,4.9216615e+07,24.9898023
2012-03-31,32.3877273,31.9777278,32.1986364,32.1949996,4.2834841e+07,26.1763101
2012-04-30,31.7935000,31.2899999,31.5374999,31.5054999,4.7036985e+07,25.6157085
2012-05-31,30.5136363,29.9890909,30.2831819,30.2263634,4.6107845e+07,24.6615301
2012-06-30,29.9628571,29.3761903,29.7085713,29.6804763,4.6339590e+07,24.2902111
2012-07-31,30.0261905,29.4404762,29.8138094,29.7571428,4.0314481e+07,24.3529523
2012-08-31,30.5213043,30.1352173,30.3373913,30.3573913,2.9206452e+07,24.9450829
2012-09-30,31.0063158,30.5468421,30.7847371,30.7821053,4.7005668e+07,25.3586598
2012-10-31,29.3447618,28.8728572,29.1514284,29.0661905,5.2638205e+07,23.9450685
2012-11-30,28.1100000,27.6004760,27.8914286,27.8119048,6.2405529e+07,23.0247898
2012-12-31,27.1934999,26.7345001,26.9910001,26.9659999,4.7365545e+07,22.3974518
2013-01-31,27.4914285,27.0261904,27.2433334,27.2366666,5.4526400e+07,22.6222627
2013-02-28,27.8963157,27.5257894,27.7231578,27.7042107,4.1083526e+07,23.0907710
2013-03-31,28.2630001,27.9340000,28.0875001,28.1410002,4.2247300e+07,23.5669010
2013-04-30,30.0877274,29.4577275,29.6422727,29.8709093,6.6625327e+07,25.0156273
2013-05-31,34.1236364,33.5768185,33.7609088,33.9509094,4.8720909e+07,28.5523396
2013-06-30,34.9535002,34.3195002,34.6524996,34.6325001,4.7257775e+07,29.2066359
2013-07-31,33.9281816,33.3340910,33.6654548,33.6504542,5.0505936e+07,28.3784462
2013-08-31,32.8090906,32.1495453,32.4740909,32.4850000,4.7784773e+07,27.5191115
2013-09-30,32.7785002,32.2390002,32.4915001,32.5234999,6.2148075e+07,27.6213285
2013-10-31,34.6317394,34.1078259,34.3552173,34.3821740,4.1970935e+07,29.1998475
2013-11-30,37.5579998,37.0425001,37.2299995,37.3625000,4.0021580e+07,31.8274126
2013-12-31,37.7789999,37.1055000,37.5135000,37.4580002,4.0455710e+07,32.0533249

In [46]:
msft.loc['1/2012', 'Adj Close'].mean()
# confirmed that 'msft_resample.mean()' has produced mean of high, low, open, close, volume and adj close for each month.

23.03384962081909